name: Build Matcha Linux ISO

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Flavor to build'
        required: true
        default: 'both'
        type: choice
        options: [both, virt, lts]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavor: [virt, lts]
        exclude:
          - flavor: ${{ github.event.inputs.flavor == 'lts' && 'virt' || '' }}
          - flavor: ${{ github.event.inputs.flavor == 'virt' && 'lts' || '' }}

    container:
      image: alpine:3.23
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Build Script
        env:
          KERNEL_FLAVOR: ${{ matrix.flavor }}
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload ISO Artifact (Local Builds Only)
        if: ${{ env.ACT == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: matcha-iso-${{ matrix.flavor }}
          path: /out/**/*.iso
          if-no-files-found: error

      - name: Upload ISO to Release
        if: ${{ env.ACT != 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          files: /out/**/*.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
