name: Build Matcha Linux ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.23
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Build Script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: matcha-iso
          path: /out/*.iso
          if-no-files-found: error
